const items = [
  {
    image: 'https://picsum.photos/200?image=15',
    title: 'Cool red phone',
    price: 256,
    retailer: 'Apple.com',
    points: 125,
    odds: '1/32',
    id: 'a1',
  },
  {
    image: 'https://picsum.photos/200?image=16',
    title: 'Light bulbs which are always turned on',
    price: 28,
    retailer: 'LightBulbs',
    points: 30,
    odds: '3/7',
    id: 'a2',
  },
  {
    image: 'https://picsum.photos/200?image=17',
    title: 'Cool red phone',
    price: 24,
    retailer: 'Apple.com',
    points: 15,
    odds: '1/3',
    id: 'a3',
  },
  {
    image: 'https://picsum.photos/200?image=18',
    title: 'Light bulbs which are always turned on',
    price: 735,
    retailer: 'LightBulbs',
    points: 157,
    odds: '1/24',
    id: 'a4',
  },
  {
    image: 'https://picsum.photos/200?image=19',
    title: 'Cool red phone',
    price: 256,
    retailer: 'Apple.com',
    points: 125,
    odds: '1/32',
    id: 'a5',
  },
  {
    image: 'https://picsum.photos/200?image=20',
    title: 'Light bulbs which are always turned on',
    price: 15,
    retailer: 'LightBulbs',
    points: 30,
    odds: '1/14',
    id: 'a6',
  },
  {
    image: 'https://picsum.photos/200?image=21',
    title: 'Cool red phone',
    price: 256,
    retailer: 'Apple.com',
    points: 125,
    odds: '1/32',
    id: 'a7',
  },
  {
    image: 'https://picsum.photos/200?image=22',
    title: 'Light bulbs which are always turned on',
    price: 15,
    retailer: 'LightBulbs',
    points: 30,
    odds: '1/14',
    id: 'a8',
  },
]

export default items
